# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PR_OAuth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Auth'
	pod 'GoogleSignIn'
  # Pods for PR_OAuth

end
